USE [MybatisDB]
GO

/****** Object:  Table [dbo].[tb_logs]    Script Date: 2017/2/4 17:40:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tb_logs](
	[USER_ID] [VARCHAR](20) NOT NULL,
	[DATED] [DATETIME] NOT NULL,
	[LOGGER] [VARCHAR](50) NOT NULL,
	[LEVEL] [VARCHAR](10) NOT NULL,
	[MESSAGE] [VARCHAR](1000) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


